//this is a database of colors from which the color will be randomly picked.
const colorsDatabase = ["green", "red", "rgba(133,122,200)", "#f15025", "pink"]; 

//Fetching the button and h2 elements by using ID and queryselector.
let clickMeButton = document.getElementById("btn"); 
let bgColor = document.querySelector(".color"); 

//adding an event listener which will execute a function based on each button click.
clickMeButton.addEventListener("click",  function(){ 
  //creating a variable which will carry the value generated by generateRandomFunc()
    let randomNumber = generateRandomFunc();   
    //console.log(randomNumber);
    document.body.style.backgroundColor = colorsDatabase[randomNumber]; // 
    bgColor.textContent = colorsDatabase[randomNumber];
    }
)

//the purpose of this function is to calculate a random whole number. I am using the colorsDatabase.length in this case to keep the number b/w [0 and (length of array)]
function generateRandomFunc(){
    return Math.floor(Math.random() * colorsDatabase.length);
}